### ISSUE TITLE
Cannot find the Windows PowerShell data file 'psake.psd1' 

### ISSUE THREAD

**Issue by ewilde** [psake/psake#126] opened 2015-01-09 19:26 UTC
When I run my [build script](https://github.com/ewilde/crane/blob/develop/build.ps1) on TeamCity I get the following error
```
System.Management.Automation.PSInvalidOperationException: Cannot find the Windows PowerShell data file 'psake.psd1' in directory 'C:\TeamCity\buildAgent\work\824ebd4bb7c8f4ec\build\en-US\', or in any parent culture directories.
```

However if I run the script locally in a normal powershell window the `$Error` variable is not polluted. I noticed that this was report in issue #19, not sure what i'm doing wrong

**Comment by damianh** [comment] 2015-02-09 08:44
There is no `psake.psd1`, I don't know how you are getting this. Also see #127

**Comment by gep13** [comment] 2015-02-26 21:58
@damianh 

I am also running into this problem, and it seems to be related to this pull request:

https://github.com/psake/psake/issues/19

Looks like the call to import-localizeddata here:

https://github.com/psake/psake/blob/5e1481351a9444ebd5d4998104e56c9bc9a733e2/psake.psm1#L838

is at the heart of the problem.  I can honestly say that I have ever used this cmd-let before, and have no idea what it is doing, or why, but if you follow the steps on that PR, you can see that the $Error variable is populated with the error described above.  I have just went as far as to comment out this line on my current failing build, however that doesn't seem to have helped.

The build still fails:

https://ci.appveyor.com/project/GaryEwanPark/chocolateygui/build/1.0.222

Yet the same code, running on a different branch works fine:

https://ci.appveyor.com/project/GaryEwanPark/chocolateygui/build/1.0.223

**NOTE:** I cancelled the second build linked above, as it got to the point of invoking psake, so I knew it was working, and there was no need to let it run further.

**Comment by gep13** [comment] 2015-02-27 07:18
Ok, so I have figured out what is going on for my situation.  @ewilde not sure if this is going to be the same for you, but possibly something that you can look into.

Let me start by saying that this was completely my fault, but I do think there is an improvement to be made to psake, but we can discuss that later.

For ChocolateyGUI, I have a conditional build step, that basically decides what psake task should be invoked.  The idea is simple:

 * If building a pull request to develop branch, run build with no deployment
 * If building develop, run build with deployment to MyGet
 * If building a pull request to master, run build with no deployment
 * If building master, run build with deployment to Chocolatey

This practice has been working great for the last 6 months or so, until last night, when I was merging into master for the first time.  I had an error in my conditional logic, which was fixed in this commit:

https://github.com/chocolatey/ChocolateyGUI/commit/7a3ca25f6299b8ffc3c27d810bee91a7488c55ab#diff-146024e5e2237b7dd58d2874e088bfc1R33

So without this fix in place, my build script was essentially doing this:

```
Import-Module psake

# Should call invoke-psake here, but it was never being called

if ($psake.build_success -eq $false) { 
  exit 1 
 } else { 
  exit 0
 }
```

As a result of not calling `invoke-psake` the `$psake.build_success` variable was defaulting to false, which was then causing a non-zero exit code.  This in itself would be fine, but due to an internal error in psake when calling `import-localizeddata` and erroring and about a value into the `$Error` variable, I was getting this weird error about a missing psd1 file, which was throwing me for a loop.  When I commented out line 838 of the psake.psm1 file, I then got the straight up `command exited with code 1` error, which then led me down the path to the actual underlying problem.

So the problem is really two fold...

 * I need to be a bit more careful in my conditional logic
 * psake needs to not pollute the `$Error` variable when there are not actually any errors in the system.  I have no idea what `import-localizeddata` and whether it is actually needed or not, but since it is set to silently continue on error, this speaks to it not actually being required, and in my opinion, could/should be removed.  This little adventure that I went on last night, speaks to the wasted effort that I and others are finding trying to hunt down issues with psake builds.

Thoughts?

**Comment by gep13** [comment] 2015-03-04 10:29
@damianh did you have any thoughts on this one?  Just wanted to check if there is anything I should do.  Thanks!

**Comment by damianh** [comment] 2015-03-06 09:27
@gep13 See #130 . Sorry, I'm taking a back seat on these things. :(

**Comment by gep13** [comment] 2015-03-06 10:05
Yip, I saw that, and I totally understand your position.  I am happy to create a pull request to remove the rogue code that is causing the error, but I don't have enough of an overview of psake as a whole to know what that PowerShell CmdLet is actually for, and whether removing it would do "bad" things or not.  I guess we would need @JamesKovacs to provide some input, but I don't know how likely that is to happen.

**Comment by dlwyatt** [comment] 2016-01-10 23:54
Import-LocalizedData is for translations, essentially.  You can have a psd1 file for each language, and psake's output could then be customized for whatever language the client's system is using.

It looks like whoever set that bit of code up defined some english-language constants in DATA section of the psake.psm1 file, then called Import-LocalizedData as a way of automatically loading up any future translation files if someone were to include them.

The easy fix (in PowerShell v3 and later), is to use `-ErrorAction Ignore` instead of `-ErrorAction SilentlyContinue`.  There's not much we can do about that sort of thing in PSv2, though.

**Closed** 2016-01-15 19:56 UTC
